services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - '9000:9000'
      - '8123:8123'
    networks:
      - hotrod-example

  otelcol:
    container_name: otelcol
    image: wesha/otel-clickhouse:0.4.0
    restart: on-failure:10
    networks:
      - hotrod-example
    depends_on:
      - clickhouse

  hotrod:
    container_name: hotrod
    image: jaegertracing/example-hotrod:latest
    ports:
      - '8080:8080'
      - '8083:8083'
    command: ['all']
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
    networks:
      - hotrod-example
    depends_on:
      - otelcol

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - '4000:4000'
    environment:
      - NAMESPACE=hotrod
      - NAME=backend
      - VERSION=0.1.0-alpha.0
      - HTTP_ADDRESS=:4000
      - STORE=clickhouse
      - STORE_ADDRESS=tcp://clickhouse:9000
      - DB=default
      - TABLE=otel_traces
    networks:
      - hotrod-example
    depends_on:
      - clickhouse

networks:
  hotrod-example:
