services:
  front:
    container_name: front
    image: wesha/toy:0.6.0
    command: server
    ports:
      - '8080:8080'
    environment:
      - NAMESPACE=toy
      - NAME=front
      - VERSION=0.6.0-rc.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol
  
  ad:
    container_name: ad
    image: wesha/toy:0.6.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=ad
      - VERSION=0.6.0-rc.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  rec:
    container_name: rec
    image: wesha/toy:0.6.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=rec
      - VERSION=0.6.0-rc.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  prod:
    container_name: prod
    image: wesha/toy:0.6.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=prod
      - VERSION=0.6.0-rc.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  cart:
    container_name: cart
    image: wesha/toy:0.6.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=cart
      - VERSION=0.6.0-rc.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  curr:
    container_name: curr
    image: wesha/toy:0.6.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=curr
      - VERSION=0.6.0-rc.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  postgres:
    container_name: postgres
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - toy-example

  redis:
    container_name: redis
    image: redis:7.0-bullseye
    networks:
      - toy-example

  ship:
    container_name: ship
    image: wesha/toy:0.6.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=ship
      - VERSION=0.6.0-rc.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  otelcol:
    container_name: otelcol
    image: wesha/otel-coll:0.5.0
    restart: on-failure:10
    networks:
      - toy-example
    depends_on:
      - clickhouse
      - prometheus

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.12.3
    ports:
      - '9000:9000'
      - '8123:8123'
    networks:
      - toy-example

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.0.0
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=remote-write-receiver"
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - toy-example
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - '4000:4000'
    environment:
      - NAMESPACE=toy
      - NAME=backend
      - VERSION=0.1.0-alpha.0
      - HTTP_ADDRESS=:4000
      - STORE=clickhouse
      - STORE_ADDRESS=tcp://clickhouse:9000
      - DB=default
      - TABLE=otel_traces
    networks:
      - toy-example
    depends_on:
      - clickhouse
      - prometheus
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - '3000:3000'
    networks:
      - toy-example
    depends_on:
      - backend

networks:
  toy-example:
