services:
  front:
    container_name: front
    image: wesha/toy:0.9.0
    command: server
    ports:
      - '8080:8080'
    environment:
      - NAMESPACE=toy
      - NAME=front
      - VERSION=0.9.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol
  
  orders:
    container_name: orders
    hostname: orders
    image: wesha/toy:0.9.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=orders
      - VERSION=0.9.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  payments:
    container_name: payments
    hostname: payments
    image: wesha/toy:0.9.0
    command: server
    environment:
      - NAMESPACE=toy
      - NAME=payments
      - VERSION=0.9.0
      - HTTP_ADDRESS=:8080
      - TRACE_ADDRESS=otelcol:4318
      - METRICS_ADDRESS=otelcol:4318
    networks:
      - toy-example
    depends_on:
      - otelcol

  # planning:
  #   container_name: planning
  #   image: wesha/toy:0.9.0
  #   command: server
  #   environment:
  #     - NAMESPACE=toy
  #     - NAME=planning
  #     - VERSION=0.9.0
  #     - HTTP_ADDRESS=:8080
  #     - TRACE_ADDRESS=otelcol:4318
  #     - METRICS_ADDRESS=otelcol:4318
  #   networks:
  #     - toy-example
  #   depends_on:
  #     - otelcol

  # risk:
  #   container_name: risk
  #   image: wesha/toy:0.9.0
  #   command: server
  #   environment:
  #     - NAMESPACE=toy
  #     - NAME=risk
  #     - VERSION=0.9.0
  #     - HTTP_ADDRESS=:8080
  #     - TRACE_ADDRESS=otelcol:4318
  #     - METRICS_ADDRESS=otelcol:4318
  #   networks:
  #     - toy-example
  #   depends_on:
  #     - otelcol

  # analytics:
  #   container_name: analytics
  #   image: wesha/toy:0.9.0
  #   command: server
  #   environment:
  #     - NAMESPACE=toy
  #     - NAME=analytics
  #     - VERSION=0.9.0
  #     - HTTP_ADDRESS=:8080
  #     - TRACE_ADDRESS=otelcol:4318
  #     - METRICS_ADDRESS=otelcol:4318
  #   networks:
  #     - toy-example
  #   depends_on:
  #     - otelcol

  # transaction:
  #   container_name: transaction
  #   image: wesha/toy:0.9.0
  #   command: server
  #   environment:
  #     - NAMESPACE=toy
  #     - NAME=transaction
  #     - VERSION=0.9.0
  #     - HTTP_ADDRESS=:8080
  #     - TRACE_ADDRESS=otelcol:4318
  #     - METRICS_ADDRESS=otelcol:4318
  #   networks:
  #     - toy-example
  #   depends_on:
  #     - otelcol

  # reporting:
  #   container_name: reporting
  #   image: wesha/toy:0.9.0
  #   command: server
  #   environment:
  #     - NAMESPACE=toy
  #     - NAME=reporting
  #     - VERSION=0.9.0
  #     - HTTP_ADDRESS=:8080
  #     - TRACE_ADDRESS=otelcol:4318
  #     - METRICS_ADDRESS=otelcol:4318
  #   networks:
  #     - toy-example
  #   depends_on:
  #     - otelcol

  # portfolio:
  #   container_name: portfolio
  #   image: wesha/toy:0.9.0
  #   command: server
  #   environment:
  #     - NAMESPACE=toy
  #     - NAME=portfolio
  #     - VERSION=0.9.0
  #     - HTTP_ADDRESS=:8080
  #     - TRACE_ADDRESS=otelcol:4318
  #     - METRICS_ADDRESS=otelcol:4318
  #   networks:
  #     - toy-example
  #   depends_on:
  #     - otelcol

  postgres:
    container_name: postgres
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - toy-example

  redis:
    container_name: redis
    image: redis:7.0-bullseye
    networks:
      - toy-example

  otelcol:
    container_name: otelcol
    image: wesha/otel-coll:0.6.0-rc.1
    restart: on-failure:10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - toy-example
    depends_on:
      - clickhouse
      - prometheus

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.12.3
    ports:
      - '9000:9000'
      - '8123:8123'
    networks:
      - toy-example

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.0.0
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=remote-write-receiver"
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - toy-example
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - '4000:4000'
    environment:
      - NAMESPACE=toy
      - NAME=backend
      - VERSION=0.1.0-alpha.0
      - HTTP_ADDRESS=:4000
      - TRACES_STORE=clickhouse
      - TRACES_STORE_ADDRESS=tcp://clickhouse:9000
      - TRACES_DB=default
      - TRACES_TABLE=otel_traces
      - METRICS_STORE_ADDRESS=http://prometheus:9090
    networks:
      - toy-example
    depends_on:
      - clickhouse
      - prometheus
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - '3000:3000'
    networks:
      - toy-example
    depends_on:
      - backend

networks:
  toy-example:
