name: Pre Merge

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Build image
          working-directory: ${{ github.workspace }}/backend
          run: | 
            docker build . --file Dockerfile
  backend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: Run tests
        working-directory: ${{ github.workspace }}/backend
        run: | 
          go clean -testcache && go test -v ./tests/unit/*